<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTR0K9r8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTR0K9r8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTR0K9r8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTR0K9r8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTR0K9r8\App_KernelDevDebugContainer([
    'container.build_hash' => 'TR0K9r8',
    'container.build_id' => 'dfd49af8',
    'container.build_time' => 1602794889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTR0K9r8');
